#!/bin/sh

bspc config border_width 4
bspc config focused_border_color '#FFFFFF'

# Escritorios
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI1 -d HP
# Reglas
bspc rule -a "oneko" layer=above
# Extras
xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0
xrandr --output HDMI1 --mode 1920x1080 --rate 74.97 --above eDP1
feh --bg-scale $HOME/Pictures/Wallpapers/01.png
polybar &
